# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CSE335 Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CSE335 Project
pod 'Firebase/Core'
pod 'Firebase/Database'

  target 'CSE335 ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CSE335 ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
